SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `taller_books` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `taller_books` ;

-- -----------------------------------------------------
-- Table `taller_books`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taller_books`.`books` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `author` VARCHAR(60) NOT NULL,
  `publish` VARCHAR(45) NOT NULL,
  `edition` VARCHAR(45) NOT NULL,
  `year` INT(4) NOT NULL,
  `origin` VARCHAR(13) NOT NULL DEFAULT 'Nacional',
  `include_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
